language: go
sudo: required
go:
  - 1.13.x
env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.13
git:
  depth: 1
before_install:
  - mkdir -p ~\/.ssh
  - openssl aes-256-cbc -K $encrypted_efc1f7a0d884_key -iv $encrypted_efc1f7a0d884_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install:
  - go version
  - go mod help
  - go mod download
script:
  - make
  - ls -la