language: go
sudo: required
go:
  - 1.13.x
env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.13
git:
  depth: 1
before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_efc1f7a0d884_key -iv $encrypted_efc1f7a0d884_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host douyacun\n\thostname ${hostname}\n\tport ${port}\n\tuser ${user}\n\tIdentityFile  ~/.ssh/id_rsa" > ~/.ssh/config
  - echo ${key} >> ~/.ssh/known_hosts
install:
  - go version
  - go mod download
script:
  - make
deploy:
  provider: script
  script: bash scripts/travis.sh
  skip_cleanup: true
#  on:
#    tags: true
notifications:
  email:
    recipients:
      - douyacun@gmail.com
    on_success: change
    on_failure: always