mysql-dsn: root:123456@tcp(192.168.1.2:3306)/douyacun?charset=utf8&parseTime=True&loc=Local
run-mode: release
dameon: on
port: :9003
pid-file: /Users/liuning/Documents/github/douyacun-go/runtime/douyacun.pid