name: Docker Image CI # Actions名称

on: # 执行时机
  push:
    branches: [ master ]

jobs:
  build: # 一个名叫build的任务（名字可以随便起）
    runs-on: ubuntu-latest # 基于最新版Ubuntu系统执行下列任务
    steps:
      - uses: actions/checkout@v1 # 将仓库内容拷贝到Ubuntu系统的虚拟环境
      - name: Build the Docker image # 步骤名字
        run: |
          docker login --username=${{ secrets.DOCKER_PASSWORD_ALI }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_USER_ALI }} # 登录docker，并使用Secret里配置的参数
          docker build -t registry.cn-hangzhou.aliyuncs.com/douyacun/api:latest . # 执行构建
          docker push registry.cn-hangzhou.aliyuncs.com/douyacun/api:latest