name: Docker Image CI # Actions名称

on: # 执行时机
  push:
    branches: [ docker ]

jobs:
  build: # 一个名叫build的任务（名字可以随便起）
    runs-on: ubuntu-latest # 基于最新版Ubuntu系统执行下列任务
    steps:
      - uses: actions/checkout@v1 # 将仓库内容拷贝到Ubuntu系统的虚拟环境
      - name: Build the Docker image # 步骤名字
        run: |
          echo ${{ secrets.DOCKER_PASSWORD_ALI }} | docker login --username=${{ secrets.DOCKER_USER_ALI }} registry.cn-hangzhou.aliyuncs.com --password-stdin
          docker build -t registry.cn-hangzhou.aliyuncs.com/douyacun/api:latest . # 执行构建
          docker push registry.cn-hangzhou.aliyuncs.com/douyacun/api:latest
      - name: Deploy to Docker Compose
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: www@myswarm.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: /root/my-deployment
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: my_applicaion
  deploy:
    runs-on: ubuntu-latest
